### ISSUE TITLE
Add Top districts entries & trends for active, recovered & deceased cases

### ISSUE THREAD

**Issue by skkart** [covid19india/covid19india-react#1669]
**Is your feature request related to a problem? Please describe.**
Currently inside state page, We show Top districts entries and its bar trend only for confirmed cases.
It would be better to show the same information for active, recovered & deceased cases too.

**Describe the solution you'd like**
On click on each cases (ex: active or recovered), Along with state map change(currently this feature exits), we can show the Top districts entries and its bar trend for the clicked case.  

**Additional context**
This feature will be useful on a long run, when user wants to know the info/trend of recovered or deceased cases.

**Comment by Binu42** [comment]
same feature is asked in #1603
