### ISSUE TITLE
Zones feature should be added 

### ISSUE THREAD

**Issue by p-balu** [covid19india/covid19india-react#2048]
The UI of the application looks great, you can also add zones (i.e red, orange,green) to the district data which were given by the government of India.
You can add zones to the district data table in such a way that if it's green zone then that specific table data of table header district should change to green color.Not the complete tr just the th :district: that specific td only or also you can do in the way that was done in the screenshot
![screen01](https://user-images.githubusercontent.com/42180197/83665499-21211280-a5e9-11ea-8991-7cc262bac443.jpg)

**Comment by shuklaayush** [comment]
Hey! We had this earlier, but there's no point in bringing it back since the government itself has stopped using zonal classification for districts.
