### ISSUE TITLE
Option to view yesterday's COVID-19 cases in the states table

### ISSUE THREAD

**Issue by TechieYash** [covid19india/covid19india-react#2325]
**Is your feature request related to a problem? Please describe.**
There should be an option to view the yesterday's covid-19 cases of all the states in the state table.

**Describe the solution you'd like**
Add an option above the table with a button 'Yesterday' which would show the covid-19 data for yesterday in the states table.

**Comment by shuklaayush** [comment]
Something like that is already there. Check this out

![Peek 2020-08-21 23-06](https://user-images.githubusercontent.com/27727946/90918985-3c8b0500-e403-11ea-93d2-634bae87c98a.gif)
