### ISSUE TITLE
Adding a feature of displaying the frequency of different statistics

### ISSUE THREAD

**Issue by AnuragVolety** [covid19india/covid19india-react#2326]
**Feature request**
As an end user, I would like to see how frequent are the different statistics (i.e Confirmed, Active, Recovered and Deceased).

**Feature Description**
I would like to have the following statistics for each statistics:

1. **Confirmed**: 1 in how many people in India is/was Covid +ve.
2. **Active**:  1 in how many people in India who is/was Covid +ve is currently Covid +ve.
3. **Recovered**: 1 in how many people in India who is/was Covid +ve has recovered.
4. **Deceased**: 1 in how many people in India who is/was Covid +ve is deceased.

**Solution**
A possible solution is to use this [API provided by Worldometers](https://rapidapi.com/aldair.sr99/api/world-population/details) to fetch the current Indian population and divide it by the confirmed count to get the statistic of "1 in how many people in India is/was Covid +ve", i.e., `1 in every (Indian population)/(Total Confirmed Cases) people in India is/was Covid +ve`.

For the rest of the statistics, just the currently fetched values are sufficient.

**Sample image for reference**
![image](https://user-images.githubusercontent.com/24853139/90925350-b379cb00-e40e-11ea-9eb3-2f2bea7a79c6.png)

**Comment by shuklaayush** [comment]
Check out the 10L button on the website
![image](https://user-images.githubusercontent.com/27727946/90930833-0c4e6100-e419-11ea-97c4-89b9a154dd2c.png)
