### ISSUE TITLE
How to use the state_data api all the city names are used as different JSON Arrays

### ISSUE THREAD

**Issue by kathan2511** [covid19india/covid19india-react#580]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by twozero88** [comment]
It is a dictionary within a dictionary.
store the main dict in a variable and then access it. 

Like in Python ->

data=requests.get('https://api.covid19india.org/v2/state_district_wise.json')
data=data.json()
nagpur_data=data['Maharashtra']['districtData']['Nagpur']

Use https://codebeautify.org/jsonviewer to get a clear picture of data.

And please raise queries in the specified format,

**Comment by kathan2511** [comment]
But how to get the nagpur as a string ?

**Comment by twozero88** [comment]
https://www.w3schools.com/python/python_dictionaries.asp

**Comment by kathan2511** [comment]
You are using names of districts as key values, there is no way to access
kay values , you have to pass them .

**Comment by twozero88** [comment]
for state in a:
    for x,y in state.items():
        if x=='districtData':
            for district in y: 
                print(district['district'])
                print(district['confirmed'])
where state => data you got from api call.

**Comment by sudevschiz** [comment]
@twozero88 thanks for the help.
However, closing this issue.
