### ISSUE TITLE
CONFIRMED case graph can never be decreasing.

### ISSUE THREAD

**Issue by linkwithsid** [covid19india/covid19india-react#761]
CONFIRMED case graph (1st graph on page) showing a dip i.e. representing decreasing cumulative confirmed cases. This graph will never be a decreasing graph. It's rate can be decreasing but not the cumulative number. 
<img width="163" alt="Screenshot 2020-04-07 at 5 16 09 PM" src="https://user-images.githubusercontent.com/13849184/78665494-87dcc500-78f3-11ea-8d6c-ca3a8374e342.png">

**Comment by shuklaayush** [comment]
@linkwithsid Yes, I agree this could be confusing. It is a plot of the rate of change of confirmed cases as you mentioned. @jeremyphilemon Should we switch it to cumulative?

**Comment by santhosh21vk** [comment]
@shuklaayush it is graph of date vs no of cases registered per that particular day.
it is similar to cumulative graph (bar graph)

**Comment by tshrwbl** [comment]
A lot of people presume its a cumulative graph. A graphical hint will be useful here. Maybe place no. of daily cases below the graph. It can be great indicative.
